// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GeoJSONPointType.
const (
	Point GeoJSONPointType = "Point"
)

// Valid indicates whether the value is a known member of the GeoJSONPointType enum.
func (e GeoJSONPointType) Valid() bool {
	switch e {
	case Point:
		return true
	default:
		return false
	}
}

// Defines values for PhotoCollectionType.
const (
	FeatureCollection PhotoCollectionType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the PhotoCollectionType enum.
func (e PhotoCollectionType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for PhotoFeatureType.
const (
	Feature PhotoFeatureType = "Feature"
)

// Valid indicates whether the value is a known member of the PhotoFeatureType enum.
func (e PhotoFeatureType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ExifData defines model for ExifData.
type ExifData struct {
	Aperture     *string `json:"aperture,omitempty"`
	FocalLength  *string `json:"focalLength,omitempty"`
	Iso          *int    `json:"iso,omitempty"`
	Make         *string `json:"make,omitempty"`
	Model        *string `json:"model,omitempty"`
	ShutterSpeed *string `json:"shutterSpeed,omitempty"`
}

// GeoJSONPoint defines model for GeoJSONPoint.
type GeoJSONPoint struct {
	Coordinates *[]float32        `json:"coordinates,omitempty"`
	Type        *GeoJSONPointType `json:"type,omitempty"`
}

// GeoJSONPointType defines model for GeoJSONPoint.Type.
type GeoJSONPointType string

// MascotSkin defines model for MascotSkin.
type MascotSkin struct {
	Animations *map[string]interface{} `json:"animations,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	ZdogConfig *map[string]interface{} `json:"zdogConfig,omitempty"`
}

// PannellumConfig Готовый JSON конфиг для pannellum.viewer()
type PannellumConfig map[string]interface{}

// PanoramaBrief defines model for PanoramaBrief.
type PanoramaBrief struct {
	DistanceM  *float32      `json:"distanceM,omitempty"`
	Id         *int64        `json:"id,omitempty"`
	Location   *GeoJSONPoint `json:"location,omitempty"`
	PreviewUrl *string       `json:"previewUrl,omitempty"`
	Title      *string       `json:"title,omitempty"`
}

// Photo defines model for Photo.
type Photo struct {
	Blurhash     *string       `json:"blurhash,omitempty"`
	CapturedAt   *time.Time    `json:"capturedAt,omitempty"`
	Exif         *ExifData     `json:"exif,omitempty"`
	Height       int           `json:"height"`
	Id           int64         `json:"id"`
	Location     *GeoJSONPoint `json:"location,omitempty"`
	OriginalUrl  *string       `json:"originalUrl,omitempty"`
	PreviewUrl   string        `json:"previewUrl"`
	ThumbnailUrl *string       `json:"thumbnailUrl,omitempty"`
	Title        *string       `json:"title,omitempty"`
	WebpUrl      *string       `json:"webpUrl,omitempty"`
	Width        int           `json:"width"`
}

// PhotoCollection defines model for PhotoCollection.
type PhotoCollection struct {
	Features *[]PhotoFeature      `json:"features,omitempty"`
	Type     *PhotoCollectionType `json:"type,omitempty"`
}

// PhotoCollectionType defines model for PhotoCollection.Type.
type PhotoCollectionType string

// PhotoFeature defines model for PhotoFeature.
type PhotoFeature struct {
	Geometry   *GeoJSONPoint     `json:"geometry,omitempty"`
	Properties *Photo            `json:"properties,omitempty"`
	Type       *PhotoFeatureType `json:"type,omitempty"`
}

// PhotoFeatureType defines model for PhotoFeature.Type.
type PhotoFeatureType string

// TileJSON defines model for TileJSON.
type TileJSON struct {
	Maxzoom  *int      `json:"maxzoom,omitempty"`
	Minzoom  *int      `json:"minzoom,omitempty"`
	Tilejson *string   `json:"tilejson,omitempty"`
	Tiles    *[]string `json:"tiles,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetNearestPanoramasParams defines parameters for GetNearestPanoramas.
type GetNearestPanoramasParams struct {
	Lon    float32  `form:"lon" json:"lon"`
	Lat    float32  `form:"lat" json:"lat"`
	Radius *float32 `form:"radius,omitempty" json:"radius,omitempty"`
}

// ListPhotosParams defines parameters for ListPhotos.
type ListPhotosParams struct {
	// Bbox minLon,minLat,maxLon,maxLat
	Bbox  *string `form:"bbox,omitempty" json:"bbox,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetNearbyPhotosParams defines parameters for GetNearbyPhotos.
type GetNearbyPhotosParams struct {
	Lon    float32  `form:"lon" json:"lon"`
	Lat    float32  `form:"lat" json:"lat"`
	Radius *float32 `form:"radius,omitempty" json:"radius,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /mascot/skins/{name})
	GetMascotSkin(w http.ResponseWriter, r *http.Request, name string)

	// (GET /panoramas/nearest)
	GetNearestPanoramas(w http.ResponseWriter, r *http.Request, params GetNearestPanoramasParams)

	// (GET /panoramas/{id}/config)
	GetPannellumConfig(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /photos)
	ListPhotos(w http.ResponseWriter, r *http.Request, params ListPhotosParams)

	// (GET /photos/nearby)
	GetNearbyPhotos(w http.ResponseWriter, r *http.Request, params GetNearbyPhotosParams)

	// (GET /photos/{id})
	GetPhoto(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /tilejson/{layer})
	GetTileJSON(w http.ResponseWriter, r *http.Request, layer string)
	// Vector tile (Mapbox Vector Tile)
	// (GET /tiles/{layer}/{z}/{x}/{y}.mvt)
	GetMVTTile(w http.ResponseWriter, r *http.Request, layer string, z int, x int, y int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /mascot/skins/{name})
func (_ Unimplemented) GetMascotSkin(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /panoramas/nearest)
func (_ Unimplemented) GetNearestPanoramas(w http.ResponseWriter, r *http.Request, params GetNearestPanoramasParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /panoramas/{id}/config)
func (_ Unimplemented) GetPannellumConfig(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /photos)
func (_ Unimplemented) ListPhotos(w http.ResponseWriter, r *http.Request, params ListPhotosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /photos/nearby)
func (_ Unimplemented) GetNearbyPhotos(w http.ResponseWriter, r *http.Request, params GetNearbyPhotosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /photos/{id})
func (_ Unimplemented) GetPhoto(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /tilejson/{layer})
func (_ Unimplemented) GetTileJSON(w http.ResponseWriter, r *http.Request, layer string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Vector tile (Mapbox Vector Tile)
// (GET /tiles/{layer}/{z}/{x}/{y}.mvt)
func (_ Unimplemented) GetMVTTile(w http.ResponseWriter, r *http.Request, layer string, z int, x int, y int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMascotSkin operation middleware
func (siw *ServerInterfaceWrapper) GetMascotSkin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMascotSkin(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNearestPanoramas operation middleware
func (siw *ServerInterfaceWrapper) GetNearestPanoramas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearestPanoramasParams

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "radius"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNearestPanoramas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPannellumConfig operation middleware
func (siw *ServerInterfaceWrapper) GetPannellumConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPannellumConfig(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPhotos operation middleware
func (siw *ServerInterfaceWrapper) ListPhotos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPhotosParams

	// ------------- Optional query parameter "bbox" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "bbox", r.URL.Query(), &params.Bbox, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bbox"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bbox", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPhotos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNearbyPhotos operation middleware
func (siw *ServerInterfaceWrapper) GetNearbyPhotos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNearbyPhotosParams

	// ------------- Required query parameter "lon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lon", r.URL.Query(), &params.Lon, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lon"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lon", Err: err})
		}
		return
	}

	// ------------- Required query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "radius"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNearbyPhotos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPhoto operation middleware
func (siw *ServerInterfaceWrapper) GetPhoto(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPhoto(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTileJSON operation middleware
func (siw *ServerInterfaceWrapper) GetTileJSON(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "layer" -------------
	var layer string

	err = runtime.BindStyledParameterWithOptions("simple", "layer", chi.URLParam(r, "layer"), &layer, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "layer", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTileJSON(w, r, layer)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMVTTile operation middleware
func (siw *ServerInterfaceWrapper) GetMVTTile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "layer" -------------
	var layer string

	err = runtime.BindStyledParameterWithOptions("simple", "layer", chi.URLParam(r, "layer"), &layer, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "layer", Err: err})
		return
	}

	// ------------- Path parameter "z" -------------
	var z int

	err = runtime.BindStyledParameterWithOptions("simple", "z", chi.URLParam(r, "z"), &z, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "z", Err: err})
		return
	}

	// ------------- Path parameter "x" -------------
	var x int

	err = runtime.BindStyledParameterWithOptions("simple", "x", chi.URLParam(r, "x"), &x, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x", Err: err})
		return
	}

	// ------------- Path parameter "y" -------------
	var y int

	err = runtime.BindStyledParameterWithOptions("simple", "y", chi.URLParam(r, "y"), &y, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "y", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMVTTile(w, r, layer, z, x, y)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/mascot/skins/{name}", wrapper.GetMascotSkin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/panoramas/nearest", wrapper.GetNearestPanoramas)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/panoramas/{id}/config", wrapper.GetPannellumConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/photos", wrapper.ListPhotos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/photos/nearby", wrapper.GetNearbyPhotos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/photos/{id}", wrapper.GetPhoto)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tilejson/{layer}", wrapper.GetTileJSON)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tiles/{layer}/{z}/{x}/{y}.mvt", wrapper.GetMVTTile)
	})

	return r
}

type GetMascotSkinRequestObject struct {
	Name string `json:"name"`
}

type GetMascotSkinResponseObject interface {
	VisitGetMascotSkinResponse(w http.ResponseWriter) error
}

type GetMascotSkin200JSONResponse MascotSkin

func (response GetMascotSkin200JSONResponse) VisitGetMascotSkinResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearestPanoramasRequestObject struct {
	Params GetNearestPanoramasParams
}

type GetNearestPanoramasResponseObject interface {
	VisitGetNearestPanoramasResponse(w http.ResponseWriter) error
}

type GetNearestPanoramas200JSONResponse []PanoramaBrief

func (response GetNearestPanoramas200JSONResponse) VisitGetNearestPanoramasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPannellumConfigRequestObject struct {
	Id int64 `json:"id"`
}

type GetPannellumConfigResponseObject interface {
	VisitGetPannellumConfigResponse(w http.ResponseWriter) error
}

type GetPannellumConfig200JSONResponse PannellumConfig

func (response GetPannellumConfig200JSONResponse) VisitGetPannellumConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhotosRequestObject struct {
	Params ListPhotosParams
}

type ListPhotosResponseObject interface {
	VisitListPhotosResponse(w http.ResponseWriter) error
}

type ListPhotos200JSONResponse PhotoCollection

func (response ListPhotos200JSONResponse) VisitListPhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNearbyPhotosRequestObject struct {
	Params GetNearbyPhotosParams
}

type GetNearbyPhotosResponseObject interface {
	VisitGetNearbyPhotosResponse(w http.ResponseWriter) error
}

type GetNearbyPhotos200JSONResponse PhotoCollection

func (response GetNearbyPhotos200JSONResponse) VisitGetNearbyPhotosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPhotoRequestObject struct {
	Id int64 `json:"id"`
}

type GetPhotoResponseObject interface {
	VisitGetPhotoResponse(w http.ResponseWriter) error
}

type GetPhoto200JSONResponse Photo

func (response GetPhoto200JSONResponse) VisitGetPhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPhoto404JSONResponse Error

func (response GetPhoto404JSONResponse) VisitGetPhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTileJSONRequestObject struct {
	Layer string `json:"layer"`
}

type GetTileJSONResponseObject interface {
	VisitGetTileJSONResponse(w http.ResponseWriter) error
}

type GetTileJSON200JSONResponse TileJSON

func (response GetTileJSON200JSONResponse) VisitGetTileJSONResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMVTTileRequestObject struct {
	Layer string `json:"layer"`
	Z     int    `json:"z"`
	X     int    `json:"x"`
	Y     int    `json:"y"`
}

type GetMVTTileResponseObject interface {
	VisitGetMVTTileResponse(w http.ResponseWriter) error
}

type GetMVTTile200ApplicationxProtobufResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMVTTile200ApplicationxProtobufResponse) VisitGetMVTTileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-protobuf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMVTTile204Response struct {
}

func (response GetMVTTile204Response) VisitGetMVTTileResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /mascot/skins/{name})
	GetMascotSkin(ctx context.Context, request GetMascotSkinRequestObject) (GetMascotSkinResponseObject, error)

	// (GET /panoramas/nearest)
	GetNearestPanoramas(ctx context.Context, request GetNearestPanoramasRequestObject) (GetNearestPanoramasResponseObject, error)

	// (GET /panoramas/{id}/config)
	GetPannellumConfig(ctx context.Context, request GetPannellumConfigRequestObject) (GetPannellumConfigResponseObject, error)

	// (GET /photos)
	ListPhotos(ctx context.Context, request ListPhotosRequestObject) (ListPhotosResponseObject, error)

	// (GET /photos/nearby)
	GetNearbyPhotos(ctx context.Context, request GetNearbyPhotosRequestObject) (GetNearbyPhotosResponseObject, error)

	// (GET /photos/{id})
	GetPhoto(ctx context.Context, request GetPhotoRequestObject) (GetPhotoResponseObject, error)

	// (GET /tilejson/{layer})
	GetTileJSON(ctx context.Context, request GetTileJSONRequestObject) (GetTileJSONResponseObject, error)
	// Vector tile (Mapbox Vector Tile)
	// (GET /tiles/{layer}/{z}/{x}/{y}.mvt)
	GetMVTTile(ctx context.Context, request GetMVTTileRequestObject) (GetMVTTileResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMascotSkin operation middleware
func (sh *strictHandler) GetMascotSkin(w http.ResponseWriter, r *http.Request, name string) {
	var request GetMascotSkinRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMascotSkin(ctx, request.(GetMascotSkinRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMascotSkin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMascotSkinResponseObject); ok {
		if err := validResponse.VisitGetMascotSkinResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNearestPanoramas operation middleware
func (sh *strictHandler) GetNearestPanoramas(w http.ResponseWriter, r *http.Request, params GetNearestPanoramasParams) {
	var request GetNearestPanoramasRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNearestPanoramas(ctx, request.(GetNearestPanoramasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNearestPanoramas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNearestPanoramasResponseObject); ok {
		if err := validResponse.VisitGetNearestPanoramasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPannellumConfig operation middleware
func (sh *strictHandler) GetPannellumConfig(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetPannellumConfigRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPannellumConfig(ctx, request.(GetPannellumConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPannellumConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPannellumConfigResponseObject); ok {
		if err := validResponse.VisitGetPannellumConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPhotos operation middleware
func (sh *strictHandler) ListPhotos(w http.ResponseWriter, r *http.Request, params ListPhotosParams) {
	var request ListPhotosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPhotos(ctx, request.(ListPhotosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPhotos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPhotosResponseObject); ok {
		if err := validResponse.VisitListPhotosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNearbyPhotos operation middleware
func (sh *strictHandler) GetNearbyPhotos(w http.ResponseWriter, r *http.Request, params GetNearbyPhotosParams) {
	var request GetNearbyPhotosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNearbyPhotos(ctx, request.(GetNearbyPhotosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNearbyPhotos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNearbyPhotosResponseObject); ok {
		if err := validResponse.VisitGetNearbyPhotosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPhoto operation middleware
func (sh *strictHandler) GetPhoto(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetPhotoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPhoto(ctx, request.(GetPhotoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPhoto")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPhotoResponseObject); ok {
		if err := validResponse.VisitGetPhotoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTileJSON operation middleware
func (sh *strictHandler) GetTileJSON(w http.ResponseWriter, r *http.Request, layer string) {
	var request GetTileJSONRequestObject

	request.Layer = layer

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTileJSON(ctx, request.(GetTileJSONRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTileJSON")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTileJSONResponseObject); ok {
		if err := validResponse.VisitGetTileJSONResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMVTTile operation middleware
func (sh *strictHandler) GetMVTTile(w http.ResponseWriter, r *http.Request, layer string, z int, x int, y int) {
	var request GetMVTTileRequestObject

	request.Layer = layer
	request.Z = z
	request.X = x
	request.Y = y

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMVTTile(ctx, request.(GetMVTTileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMVTTile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMVTTileResponseObject); ok {
		if err := validResponse.VisitGetMVTTileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
