/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { GeoJSONPointType } from './geoJSONPointType';

export interface GeoJSONPoint {
  type?: GeoJSONPointType;
  /**
   * @minItems 2
   * @maxItems 3
   */
  coordinates?: number[];
}
