/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */

export type GeoJSONPointType = typeof GeoJSONPointType[keyof typeof GeoJSONPointType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeoJSONPointType = {
  Point: 'Point',
} as const;
