/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */

export type ListPhotosParams = {
/**
 * minLon,minLat,maxLon,maxLat
 */
bbox?: string;
limit?: number;
};
