/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { MascotSkinZdogConfig } from './mascotSkinZdogConfig';
import type { MascotSkinAnimations } from './mascotSkinAnimations';

export interface MascotSkin {
  name?: string;
  zdogConfig?: MascotSkinZdogConfig;
  animations?: MascotSkinAnimations;
}
