/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { GeoJSONPoint } from './geoJSONPoint';

export interface PanoramaBrief {
  id?: number;
  title?: string;
  previewUrl?: string;
  distanceM?: number;
  location?: GeoJSONPoint;
}
