/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */

export type PhotoCollectionType = typeof PhotoCollectionType[keyof typeof PhotoCollectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhotoCollectionType = {
  FeatureCollection: 'FeatureCollection',
} as const;
