/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoFeatureType } from './photoFeatureType';
import type { GeoJSONPoint } from './geoJSONPoint';
import type { Photo } from './photo';

export interface PhotoFeature {
  type?: PhotoFeatureType;
  geometry?: GeoJSONPoint;
  properties?: Photo;
}
