/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */

export type PhotoFeatureType = typeof PhotoFeatureType[keyof typeof PhotoFeatureType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhotoFeatureType = {
  Feature: 'Feature',
} as const;
