/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { GeoJSONPoint } from './geoJSONPoint';
import type { ExifData } from './exifData';

export interface Photo {
  id: number;
  title?: string;
  originalUrl?: string;
  previewUrl: string;
  thumbnailUrl?: string;
  webpUrl?: string;
  blurhash?: string;
  width: number;
  height: number;
  capturedAt?: string;
  location?: GeoJSONPoint;
  exif?: ExifData;
}
