/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GeoMap API
 * MapLibre + Pannellum + Photos backend
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoCollectionType } from './photoCollectionType';
import type { PhotoFeature } from './photoFeature';

export interface PhotoCollection {
  type?: PhotoCollectionType;
  features?: PhotoFeature[];
}
